learning_users/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

#TEMPLATE URLS

app_name = 'basicapp'

urlpatterns= [
	url(r'^register/$',views.register,name='register'),
	url(r'^userlogin/$',views.userlogin,name='userlogin'),
]

learning_users/learning_users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basicapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'basicapp/', include('basicapp.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/',views.special,name='special')
]

learning_users/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

	user = models.OneToOneField(User)

	#additional 
	portfolio_site = models.URLField(blank=True)

	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

	def __str__(self):
		return self.user.username

learning_users/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site','profile_pic')

learning_users/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm
# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required



def index(request):
	return render(request,'basicapp/index.html')


@login_required
def special(request):
	return render(request,'basicapp/special.html')


@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))


def register(request):
	registered = False

	if request.method == "POST":
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit=False)
			profile.user = user

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']

			profile.save()

			registered = True
		else:
			print(user_form.errors,profile_form.errors)

	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm

	return render(request,'basicapp/registration.html',
					{'user_form':user_form, 'profile_form':profile_form, 'registered':registered})


def userlogin(request):

	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username,password=password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))

			else:
				return HttpResponse('account not active')
		else:
			print('someone tried to login and failed')
			print('Username: {} and password {}'.format(username,password))
			return HttpResponse('invalid login details supplied')

	else:
		return render(request,'basicapp/login.html')

learning_users/templates/basicapp/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
	<nav class='navbar navbar-default navbar-static-top'>
		<div class="container">
			<ul class='nav navbar-nav'>
				<li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
				<li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
				<li><a class="navbar-link" href="{% url 'basicapp:register' %}">Register</a></li>

				{% if user.is_authenticated %}
				<li><a class='navbar-link' href="{% url 'logout' %}">Log Out</a></li>
				<li><a class='navbar-link' href="{% url 'special' %}">Special</a></li>
				{% else %}
				<li><a class='navbar-link' href="{% url 'basicapp:userlogin' %}">Log In</a></li>
				{% endif %}
			</ul>
		</div>
	</nav>

	{% block body_block %}
	{% endblock %}
</body>
</html>

learning_users/templates/basicapp/index.html
{% extends "basicapp/base.html" %}
{% block body_block %}
<div class="container">
<div class="jumbotron">
	<h1>Website Home Page</h1>
	<div class="tenor-gif-embed" data-postid="12469724" data-share-method="host" data-width="75%" data-aspect-ratio="1.0"><a href="https://tenor.com/view/idk-chief-idont-know-about-that-one-chief-chief-gif-12469724">Idk Chief IDont Know About That One Chief GIF</a> from <a href="https://tenor.com/search/idkchief-gifs">Idkchief GIFs</a></div><script type="text/javascript" async src="https://tenor.com/embed.js"></script>
</div>
</div>
{% endblock %}

learning_users/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block body_block %}
<div class="container">
	<div class="jumbotron">
		<h1>Please Login</h1>
		<form action="{% url 'basicapp:userlogin'%}" method ="post">
			{% csrf_token %}
			<label for="username">Username:</label>
			<input type="text" name="username" placeholder="enter username">
			<label for="password">Password:</label>
			<input type="password" name="password">
			<input type="submit" name="login">
		</form>
	</div>
</div>
{% endblock %}

learning_users/templates/basicapp/registration.html
{% extends 'basicapp/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="container">
<div class="jumbotron">
	{% if registered %}
		<div class="container">
		<h1>Thank you for registering!</h1>
		</div>
	{% else %}
		<h1>Register Here!</h1>
		<h3>Fill out the form:</h3>

		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{ user_form.as_p }}
			{{ profile_form.as_p }}
			<input type="submit" name="" value="Register">
		</form>
	{% endif %}
</div>
</div>
{% endblock %}

learning_users/templates/basicapp/special.html
{% extends 'basicapp/base.html' %}
<!-- inheriting from the base html template, the navigation bar. 
Then, beginning content that will be palced inside the bodyblock tags in base.html -->
{% block body_block %}

<!-- bootstrap 3.0 class used to make it look neat -->
<div class="container">
	<h1>This page can only be viewed by registered users</h1>
	<h2>Congratulations on adding your credentials to the database</h2>
	<h2>Additional content is in the making</h2>
	<a href="{% url 'index' %}">Click here to go back to the main page</a>
</div>


{% endblock %}